SELECT * FROM STUDENTS;

--1.25살이고 부산에 사는사람

SELECT *
FROM STUDENTS
WHERE SAGE >= 25 AND SADDR = '부산'
;

--2. 이름이 김으로 시작하는 애

SELECT *
FROM STUDENTS
WHERE SNAME LIKE '김%%'
;

--3.부산살면서 번호가 4444로 끝나는애

SELECT *
FROM STUDENTS
WHERE STEL LIKE '%4444' AND SADDR = '부산'
;

--지역별, 나이별, 출신별, 그룹을 만든다
--집계함수 내장함수(오라클이 지원하는 함수)

--1. 데이터의 개수를 센다.                  --> COUNT(FIELD 값)
--2. 내가 원하는 데이터의 합계를 구할 수 있다. --> SUM()
--3. 내가 원하는 데이터의 평균을 구할 수 있다. --> AVG()
--4. MAX
--5. MIN

--현재 STUDENTS 테이블의 총 ROW 수가 몇개냐
SELECT COUNT(*) FROM STUDENTS;

SELECT COUNT(SNAME) FROM STUDENTS
WHERE SADDR = '부산'
;

--현재 테이블에 등록된 학생들의 평균 나이
SELECT AVG(SAGE) FROM STUDENTS
WHERE SADDR = '부산'
;

SELECT SUM(SAGE) FROM STUDENTS
;

SELECT COUNT(*), AVG(SAGE), SUM(SAGE) FROM STUDENTS;

--GROUP
SELECT SADDR, COUNT(*) FROM STUDENTS
--WHERE SADDR = '부산'
GROUP BY SADDR
;

--지역별 평균나이
SELECT SADDR, AVG(SAGE) 
FROM STUDENTS
WHERE SAGE > 25
GROUP BY SADDR;

--남성 여성 숫자
SELECT SGENDER, COUNT(SGENDER) FROM STUDENTS
--WHERE SGENDER = 'M' OR SGENDER = 'F'
GROUP BY SGENDER
;

--지역별, 성별 숫자
SELECT SGENDER, COUNT(*) 
FROM STUDENTS
GROUP BY SGENDER
;

SELECT MAX(BIRTH) FROM PROFESSORS;

SELECT SUBSTR(BIRTH, 4, 1) FROM PROFESSORS;

SELECT * FROM PROFESSORS
WHERE SUBSTR (BIRTH, 3, 1) LIKE 8;

-- 1970년생 : 1980년생 :
SELECT *FROM PROFESSORS
GROUP BY BITRH
;

UPDATE SUBJECTS
SET SUBID = 'SUB' || SUBSTR(SUBID, 4, 1)
;

UPDATE EXAMS
SET SUBID = 'SUB' || SUBSTR(SUBID, 4, 1)
;

SELECT * FROM PROFESSORS;
SELECT * FROM EXAMS
WHERE PID = 'P001'
;

INSERT INTO EXAMS VALUES('P001', 'SUB6', '음악시험 ㅗ');

--COMMIT;

--PL SQL
--TRANSACT SQL --> T SQL

SELECT *
FROM PROFESSORS T1, EXAMS T2
WHERE T1.PID = T2.PID
AND T1.PID = 'P001'
;