--랭크함수

--정규화 되어있는 테이블
CREATE TABLE SALLARY
(
    IDX   NUMBER(5)    NOT NULL PRIMARY KEY,
    PART  VARCHAR2(30) NOT NULL,
    ENAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER(10)   NOT NULL
);

INSERT INTO SALLARY VALUES(1, '인사과', '홍길동', 2000000);
INSERT INTO SALLARY VALUES(2, '인사과', '전우치', 3000000);
INSERT INTO SALLARY VALUES(3, '인사과', '우투리', 4000000);
INSERT INTO SALLARY VALUES(4, '총무부', '온달', 5500000);
INSERT INTO SALLARY VALUES(5, '총무부', '이성계', 5600000);
INSERT INTO SALLARY VALUES(6, '총무부', '김의민', 5100000);
INSERT INTO SALLARY VALUES(7, '생산과', '김시민', 5300000);
INSERT INTO SALLARY VALUES(8, '생산과', '권율', 5040000);
INSERT INTO SALLARY VALUES(9, '구매과', '임꺽정', 5000000);
INSERT INTO SALLARY VALUES(10, '구매과', '최영', 5600000);

SELECT * FROM SALLARY;
--COMMIT;

UPDATE SALLARY SET PRICE = 5500000
WHERE IDX = 10
;

--ROW_NUMBER()
SELECT
    IDX, PART, ENAME, PRICE, 
    ROW_NUMBER() OVER(ORDER BY PRICE ASC) AS ROW_NUM,
    RANK() OVER(ORDER BY PRICE DESC) AS RNK,
    DENSE_RANS() OVER(ORDER BY PRICE ASC) AS DENSERNK
    
FROM SALLARY
;