--datatype date
SELECT SYSDATE FROM DUAL;
--SYSDATE 는 시,분,초 모두 포함함

CREATE TABLE DATE_TEST
(
    NAME VARCHAR2(30) NOT NULL,
    INDATE DATE NOT NULL
);

INSERT INTO DATE_TEST VALUES('홍길동', SYSDATE);
INSERT INTO DATE_TEST VALUES('전우치', '2021-04-11');
INSERT INTO DATE_TEST VALUES('전우치', '2021-04-10');

--COMMIT;

SELECT * FROM DATE_TEST;

--1. DATE - TO_CHAR 활용
SELECT NAME, TO_CHAR(INDATE, 'YYYY-MM-DD HH:MI:SS') FROM DATE_TEST;

--2.DATE TYPE 원리 -- ORACLE ENGINE --> 숫자
SELECT SYSDATE + 1 FROM DUAL;

SELECT INDATE, TO_CHAR(INDATE, 'YYYY-MM-DD HH:MI:SS') FROM DATE_TEST;

--년
SELECT INDATE, TO_CHAR(INDATE, 'YYYY') FROM DATE_TEST;

SELECT INDATE, TO_CHAR(INDATE, 'YYYY')AS INYEAR FROM DATE_TEST;
SELECT INDATE, TO_CHAR(INDATE, 'MM')AS INMONTH FROM DATE_TEST;
SELECT INDATE, TO_CHAR(INDATE, 'DL')AS INDAY FROM DATE_TEST;

--요일
SELECT INDATE, TO_CHAR(INDATE, 'MON')AS INMONTH FROM DATE_TEST;

--2021년 4월 1일부터 4월 30일까지 날짜를 모두 표시하고 출석한 횟수를 보여주세요
SELECT SYSDATE, LEVEL, SYSDATE - LEVEL
FROM DUAL
CONNECT BY LEVEL <= 10
ORDER BY LEVEL DESC
;

UPDATE DATE_TEST
SET INDATE = '2021-04-12'
WHERE NAME = '전우치'
;
--ROLLBACK;
SELECT * FROM DATE_TEST;

SELECT TO_CHAR(INDATE, 'YYYY-MM-DD'), COUNT(*)
FROM DATE_TEST
GROUP BY TO_CHAR(INDATE, 'YYYY-MM-DD')
ORDER BY TO_CHAR(INDATE, 'YYYY-MM-DD')
;

SELECT TO_DATE('2021-04-01') + (LEVEL -1) AS MDATE
FROM DUAL
CONNECT BY LEVEL <= 30
;

SELECT MDATE, COUNT(T2.INDATE)
FROM (SELECT TO_DATE('2021-04') + (LEVEL -1) AS MDATE FROM DATE_TEST CONNECT BY LEVEL <= 12) T1,
DATE_TEST T2
WHERE TO_CHAR(MDATE, 'YYYY-MM-DD') = TO_CHAR(T2.INDATE(+), 'YYYY-MM-DD')
CONNECT BY LEVEL < 12
GROUP BY MDATE
ORDER BY MDATE
;

SELECT *
FROM DATE_TEST T1, (SELECT TO_DATE('2021-04-01', MM) FROM DATE_TEST) T2
WHERE TO_CHAR(T1.INDATE, 'YYYY-MM-DD') = TO_CHAR(T2, 'YYYY-MM-DD')
;

SELECT*FROM DATE_TEST;

SELECT ADD_MONTHS(INDATE, LEVEL-4)
FROM DATE_TEST
CONNECT BY LEVEL <= 12
;

SELECT ADD_MONTHS(TO_DATE(SYSDATE, 'YYYY-MM-DD'), 1)
FROM DUAL;

SELECT *
FROM ;

--2021년 1월부터 12월까지

SELECT TO_CHAR((SYSDATE - 101) + (LEVEL -1))
FROM DUAL
CONNECT BY LEVEL <= 365;

SELECT TO_DATE('2021-04-01')
FROM (SELECT TO_DATE('2021-04') + (LEVEL -1) AS MDATE FROM DATE_TEST CONNECT BY LEVEL <= 12) T1,
DATE_TEST T2
WHERE TO_CHAR(T1.MDATE) = TO_CHAR(T2.INDATE(+))
CONNECT BY LEVEL <= 12
;

SELECT TO_CHAR(TO_DATE(SYSDATE, 'YYYY-MM-DD'), 'YYYYMM') + (LEVEL - 4), COUNT(T2.INDATE)
FROM DUAL T1, DATE_TEST T2
WHERE T1.TO_CHAR(TO_DATE(SYSDATE, 'YYYY-MM-DD'), 'YYYYMM') + (LEVEL - 4)(+) = T2.INDATE
CONNECT BY LEVEL <= 12
GROUP BY TO_CHAR(TO_DATE(SYSDATE, 'YYYY-MM-DD'), 'YYYYMM') + (LEVEL - 4)
ORDER BY TO_CHAR(TO_DATE(SYSDATE, 'YYYY-MM-DD'), 'YYYYMM') + (LEVEL - 4)
;


SELECT
ADD_MONTHS(TO_CHAR(TO_DATE('2021-01-01', 'YYYY-MM-DD'), 'YY-MM'), LEVEL - 4)
FROM DUAL
CONNECT BY LEVEL <= 12
;

SELECT TO_CHAR(TO_CHAR)