SELECT * FROM BOOKS;
SELECT * FROM BSTORES;
SELECT * FROM BUY_BOOK;
SELECT * FROM CUSTOMERS;
SELECT * FROM GENRES;
SELECT * FROM HOLD_BOOK;
SELECT * FROM PRICE_BOOK;
SELECT * FROM SELL_BOOK;

SELECT TO_NUMBER(TO_CHAR(SUBSTR(BK_CODE, 3), 'FM00'))
FROM BOOKS
;



SELECT 'BK' || TO_CHAR(TO_NUMBER(TO_CHAR(SUBSTR(MAX(BK_CODE), 3), 'FM00')) + 1)
FROM BOOKS
;

    SELECT SB_CNT
    FROM SELL_BOOK
    WHERE BS_CODE = 'BS01'
    AND BK_CODE = 'BK01'
    AND CR_CODE = 'CR01'
    AND SB_IDX = 1
    ;