--랭크함수

--정규화 되어있는 테이블
CREATE TABLE SALLARY
(
    IDX   NUMBER(5)    NOT NULL PRIMARY KEY,
    PART  VARCHAR2(30) NOT NULL,
    ENAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER(10)   NOT NULL
);

INSERT INTO SALLARY VALUES(1, '인사과', '홍길동', 2000000);
INSERT INTO SALLARY VALUES(2, '인사과', '전우치', 3000000);
INSERT INTO SALLARY VALUES(3, '인사과', '우투리', 4000000);
INSERT INTO SALLARY VALUES(4, '총무부', '온달', 5500000);
INSERT INTO SALLARY VALUES(5, '총무부', '이성계', 5600000);
INSERT INTO SALLARY VALUES(6, '총무부', '김의민', 5100000);
INSERT INTO SALLARY VALUES(7, '생산과', '김시민', 5300000);
INSERT INTO SALLARY VALUES(8, '생산과', '권율', 5040000);
INSERT INTO SALLARY VALUES(9, '구매과', '임꺽정', 5000000);
INSERT INTO SALLARY VALUES(10, '구매과', '최영', 5600000);

SELECT * FROM SALLARY;
--COMMIT;

UPDATE SALLARY SET PRICE = 5200030
WHERE IDX = 1
;

--ROW_NUMBER()
SELECT
    IDX, PART, ENAME, PRICE, 
    ROW_NUMBER() OVER(ORDER BY PRICE ASC) AS ROW_NUM,
    RANK() OVER(ORDER BY PRICE DESC) AS RNK,
    DENSE_RANS() OVER(ORDER BY PRICE ASC) AS DENSERNK
    
FROM SALLARY
;

SELECT * FROM SALLARY
ORDER BY PART ASC, ENAME ASC
;

SELECT PART, SUM(PRICE),
        RANK() OVER(ORDER BY SUM(PRICE)DESC),
        RANK() OVER(ORDER BY AVG(PRICE)DESC)        
FROM SALLARY
GROUP BY PART
;

SELECT * 
FROM SALLARY
;

--전체평균 월급과 10명 각각의 월급 차이

SELECT ENAME, PRICE,PRICE - (SELECT AVG(PRICE) FROM SALLARY)
FROM SALLARY
GROUP BY ENAME, PRICE
;

--각 부서별 평균월급의 순위

SELECT PART, ROUND(AVG(PRICE),0),
        RANK() OVER(ORDER BY AVG(PRICE)DESC)
FROM SALLARY 
GROUP BY PART
;

--평균 월급이 3위인 부서의 월급보다 많은 월급을 받고 있는 사원들을 보여주세요

SELECT T2.ENAME, T2.PRICE
FROM
(
SELECT PART, ROUND(AVG(PRICE), 2),
        RANK() OVER(ORDER BY AVG(PRICE) DESC)AS RNK
FROM SALLARY
GROUP BY PART
)T1, SALLARY T2
WHERE T1.PART = T2.PART
AND RNK < 3
;

