CREATE OR REPLACE PROCEDURE PROC_CHECK_CUSTOMER
(
    IN_PRICE        IN VARCHAR2
)
IS

    V_IN_PRICE      VARCHAR2(50);

BEGIN

    SELECT 
    INTO V_IN_PRICE
    FROM SALES_TBL T1
    WHERE S_PRICE <= 1000
    ;

END PROC_CHECK_CUSTOMER;